[versions]
activity-compose = "1.12.1"

android = "4.1.1.4"
android-plugin = "8.9.3"
constraintlayout = "2.2.1"

fastjson = "2.0.60"
hiddenapibypass = "6.1"
kotlin = "2.2.21"
kotlinxCoroutinesCore = "1.10.2"
kotlinxSerializationJson = "1.9.0"
lifecycleLivedataKtx = "2.10.0"
nanohttpd = "2.3.1"
shizukuVersion = "13.1.5"
hiddenapi = "4.4.0"
slf4j = "2.1.0-alpha1"
logback-android = "3.0.0"
appcompat = "1.7.1"
recyclerview = "1.4.0"
viewpager2 = "1.1.0"
material = "1.13.0"
lombok = "1.18.42"
okhttp = "5.3.2"
jackson = "2.20.1"
jackson-annotations = "2.20"
xposed-api = "100"
xposed-service = "100-1.0.0"

#noinspection GradleDependency
jackson-compatible = "2.13.5"
webkit = "1.14.0"
core-ktx = "1.17.0"
dexkit = "2.0.7"
ui-tooling-preview-android = "1.10.0"
desugar = "2.1.5"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
fragment = "1.8.9"
[libraries]

android = { module = "com.google.android:android", version.ref = "android" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleLivedataKtx" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
fastjson = { module = "com.alibaba:fastjson", version.ref = "fastjson" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
rikka-shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizukuVersion" }
rikka-shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizukuVersion" }
rikka-refine = { module = "dev.rikka.tools.refine:runtime", version.ref = "hiddenapi" }
rikka-hidden-stub = { module = "dev.rikka.hidden:stub", version.ref = "hiddenapi" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logback-android" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }

viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson-annotations" }

dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "ui-tooling-preview-android" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }



[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
rikka-tools-refine = { id = "dev.rikka.tools.refine", version.ref = "hiddenapi" }

