[versions]
activity-compose = "1.10.1"

android-plugin = "8.9.3"
constraintlayout = "2.1.4"

hiddenapibypass = "6.1"
kotlin-plugin = "2.2.0-Beta2"
kotlin-stdlib = "2.1.20"
kotlinxCoroutinesCore = "1.10.2"
kotlinxSerializationJson = "1.9.0"
lifecycleLivedataKtx = "2.9.4"
mmkv = "2.2.3"
nanohttpd = "2.3.1"
shizukuVersion = "13.1.5"
work = "2.10.0"
hiddenapi = "4.4.0"
slf4j = "2.1.0-alpha1"
logback-android = "3.0.0"
appcompat = "1.7.0"
recyclerview = "1.4.0"
viewpager2 = "1.1.0"
material = "1.13.0-alpha13"
lombok = "1.18.38"
okhttp = "5.0.0-alpha.14"
jackson = "2.19.2"

xposed-api = "100"
xposed-service = "100-1.0.0"

#noinspection GradleDependency
jackson-compatible = "2.13.5"
webkit = "1.14.0-beta01"
core-ktx = "1.16.0"
dexkit = "2.0.4"
ui-tooling-preview-android = "1.8.1"
desugar = "2.1.5"
[libraries]

androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleLivedataKtx" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-stdlib" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
rikka-shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizukuVersion" }
rikka-shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizukuVersion" }
rikka-refine = { module = "dev.rikka.tools.refine:runtime", version.ref = "hiddenapi" }
rikka-hidden-stub = { module = "dev.rikka.hidden:stub", version.ref = "hiddenapi" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logback-android" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }

viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
#xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposed-api" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
#noinspection SimilarGradleDependency
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
#noinspection SimilarGradleDependency
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
#noinspection SimilarGradleDependency
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
#noinspection SimilarGradleDependency
jackson-core-compatible = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson-compatible" }
#noinspection SimilarGradleDependency
jackson-databind-compatible = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-compatible" }
#noinspection SimilarGradleDependency
jackson-annotations-compatible = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson-compatible" }

#noinspection Aligned16KB
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "ui-tooling-preview-android" }

libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "xposed-api" }
libxposed-service = { group = "io.github.libxposed", name = "service", version.ref = "xposed-service" }


[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-plugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version = "2.0.0" }
rikka-tools-refine = { id = "dev.rikka.tools.refine", version.ref = "hiddenapi" }

